### ISSUE TITLE
[BUG]I cant find where the buildings are

### ISSUE THREAD

**Issue by Baller3** [SpaceGameDev568/ObstacleMod#2]
the buildings wont show up for some reason. maybe it was a mistake on my end

**Comment by SpaceGameDev568** [comment]
Did you unlock the schematic in HUB Tier 1?

**Comment by SpaceGameDev568** [comment]
I can't reproduce the issue on my own, so I will have to assume that you've incorrectly used the mod. I can refer you to the documentation on the mod page (https://ficsit.app/mod/ObstacleMod) and if the issue persists then try removing and reinstalling the mod.

Regards,

SpaceGameDev
